name = "brinn-mcp"
main = "src/worker.ts"
compatibility_date = "2024-11-20"

[vars]
BRINN_API_URL = "https://api.memo.opstintechnologies.com/api" # User should specify their URL if different

[observability]
enabled = true
